name: Trigger Event

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  trigger:
    runs-on: ubuntu-latest
    
    steps:
      - name: Dispatch event
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.DISPATCH_TOKEN }}
          repository: bhardwaj-addweb/tas2
          event-type: repo-updated
